info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:32:30.832Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:32:30.876Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" length must be at least 4 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-03-01T07:33:27.863Z"}
error: getaddrinfo ENOTFOUND naluzotan.com {"code":"EDNS","command":"CONN","errno":-3008,"hostname":"naluzotan.com","syscall":"getaddrinfo","timestamp":"2022-03-01T07:34:22.247Z"}
error: getaddrinfo ENOTFOUND naluzotan.com {"code":"EDNS","command":"CONN","errno":-3008,"hostname":"naluzotan.com","syscall":"getaddrinfo","timestamp":"2022-03-01T07:37:48.378Z"}
error: getaddrinfo ENOTFOUND naluzotan.com {"code":"EDNS","command":"CONN","errno":-3008,"hostname":"naluzotan.com","syscall":"getaddrinfo","timestamp":"2022-03-01T07:37:49.093Z"}
error: getaddrinfo ENOTFOUND naluzotan.com {"code":"EDNS","command":"CONN","errno":-3008,"hostname":"naluzotan.com","syscall":"getaddrinfo","timestamp":"2022-03-01T07:37:49.936Z"}
error: getaddrinfo ENOTFOUND naluzotan.com {"code":"EDNS","command":"CONN","errno":-3008,"hostname":"naluzotan.com","syscall":"getaddrinfo","timestamp":"2022-03-01T07:37:50.740Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:38:30.302Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:38:30.325Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":1048,"messageId":"<a8bbf8d6-8665-91ee-a6b4-9800863affb9@LAPTOP>","messageSize":549,"messageTime":805,"rejected":[],"response":"250 2.0.0 OK  1646120181 c18-20020a056a000ad200b004cdccd3da08sm15808982pfl.44 - gsmtp","timestamp":"2022-03-01T07:38:45.015Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":902,"messageId":"<3e8fb3da-a09d-f956-2c74-fd5ac8caa7d5@LAPTOP>","messageSize":549,"messageTime":762,"rejected":[],"response":"250 2.0.0 OK  1646120182 t8-20020a6549c8000000b00372eb3a7fb3sm12085162pgs.92 - gsmtp","timestamp":"2022-03-01T07:38:45.665Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":919,"messageId":"<0266e815-0a21-c190-5014-dec559a1a07f@LAPTOP>","messageSize":549,"messageTime":3479,"rejected":[],"response":"250 2.0.0 OK  1646120185 me8-20020a17090b17c800b001bce9d8e61fsm1367012pjb.50 - gsmtp","timestamp":"2022-03-01T07:38:49.297Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:41:13.832Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:41:13.859Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:41:21.380Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:41:21.406Z"}
error: 
    status - 500 
    message - TypeError: req.status is not a function
    at _callee$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:8:9)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/getallusers 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T07:41:43.226Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:42:01.602Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:42:01.624Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:42:54.750Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:42:54.771Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":1121,"messageId":"<2b1358a6-b069-8494-ca9e-45ccc31c1173@LAPTOP>","messageSize":549,"messageTime":1025,"rejected":[],"response":"250 2.0.0 OK  1646120591 e18-20020a056a001a9200b004bc82d0e125sm15177659pfv.119 - gsmtp","timestamp":"2022-03-01T07:45:34.608Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:51:32.575Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:51:32.598Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'emailID')
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:52:17)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/forget 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T07:51:46.377Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:52:41.645Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:52:41.744Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:52:57.974Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:52:58.006Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":1212,"messageId":"<d8963942-2df8-6453-00bd-d0062244843f@LAPTOP>","messageSize":549,"messageTime":936,"rejected":[],"response":"250 2.0.0 OK  1646121051 q11-20020a63f94b000000b00373c5319642sm11685139pgk.93 - gsmtp","timestamp":"2022-03-01T07:53:14.609Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:54:08.971Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:54:08.998Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T07:54:18.876Z"}
info: Connected to the database. {"timestamp":"2022-03-01T07:54:18.900Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":1124,"messageId":"<5e019b0a-6b81-9e9e-14de-412ab4e813f9@LAPTOP>","messageSize":549,"messageTime":1001,"rejected":[],"response":"250 2.0.0 OK  1646121581 oc3-20020a17090b1c0300b001bce36844c7sm1448329pjb.17 - gsmtp","timestamp":"2022-03-01T08:02:04.498Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T08:23:53.140Z"}
info: Connected to the database. {"timestamp":"2022-03-01T08:23:53.166Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T08:24:00.389Z"}
info: Connected to the database. {"timestamp":"2022-03-01T08:24:00.410Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T08:29:28.767Z"}
info: Connected to the database. {"timestamp":"2022-03-01T08:29:28.788Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T08:30:21.357Z"}
info: Connected to the database. {"timestamp":"2022-03-01T08:30:21.380Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:07:32.407Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:07:32.430Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:07:54.433Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:07:54.461Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:08:26.933Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:08:26.957Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:09:30.671Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:09:30.696Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:10:54.713Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:10:54.734Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:11:16.066Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:11:16.089Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:17:16.814Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:17:16.835Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:20:51.113Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:20:51.134Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:20:58.166Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:20:58.192Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:21:53.895Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:21:53.916Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:23:18.694Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:23:18.715Z"}
error: 
      status - 400
      message - Authorization token is incorrect 
      url - /api/v1/note 
      method - POST 
      IP - ::1
     {"timestamp":"2022-03-01T12:34:35.016Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:35:18.641Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:35:18.663Z"}
error: 
      status - 400
      message - Authorization token is incorrect 
      url - /api/v1/note 
      method - POST 
      IP - ::1
     {"timestamp":"2022-03-01T12:36:47.450Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:37:14.644Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:37:14.666Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:38:41.801Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:38:41.823Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:41:24.184Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:41:24.209Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:42:07.168Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:42:07.196Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:46:11.983Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:46:12.007Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:47:44.593Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:47:44.615Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:48:04.648Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:48:04.679Z"}
error: 
      status - 400
      message - Authorization token is incorrect 
      url - /api/v1/users/reset 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-03-01T12:48:19.621Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:48:46.638Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:48:46.664Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:52:52.603Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:52:52.629Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:53:00.100Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:53:00.128Z"}
error: 
    status - 500 
    message - ReferenceError: UserID is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:69:9)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:74:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T12:53:04.801Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:54:33.428Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:54:33.454Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:54:43.322Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:54:43.424Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:54:51.184Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:54:51.213Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:55:09.652Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:55:09.678Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T12:55:10.918Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T12:55:57.600Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T12:56:00.332Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:57:28.775Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:57:28.807Z"}
error: 
    status - 500 
    message - ReferenceError: UserID is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:69:7)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T12:57:29.388Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T12:57:57.213Z"}
info: Connected to the database. {"timestamp":"2022-03-01T12:57:57.239Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:00:43.780Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:00:43.809Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T13:00:48.718Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:01:21.230Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:01:21.253Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:01:33.379Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:01:33.407Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:01:47.598Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:01:47.625Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:02:03.267Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:02:03.295Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ password: 'asdfghjkl' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T13:02:36.315Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ password: 'asdfghjkl' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T13:02:39.716Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:06:27.441Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:06:27.469Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:08:28.701Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:08:28.726Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:08:59.278Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:08:59.300Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:09:38.740Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:09:38.764Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:10:56.451Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:10:56.484Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:11:41.855Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:11:41.883Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:12:20.932Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:12:20.963Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:12:51.468Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:12:51.491Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:13:20.894Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:13:20.919Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:14:23.179Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:14:23.218Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:49:52.349Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:49:52.374Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTIxNzIwfQ.TCoU265hBsUzrtNjeUH_Ehb8zxc7MKgptqWSfqednPs 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-03-01T13:50:19.764Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:50:47.072Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:50:47.099Z"}
error: 
    status - 500 
    message - ReferenceError: userID is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:66:51)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T13:51:02.252Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:52:42.561Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:52:42.591Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T13:52:46.109Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T13:53:31.882Z"}
info: Connected to the database. {"timestamp":"2022-03-01T13:53:31.908Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:00:01.701Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:00:01.731Z"}
error: 
    status - 500 
    message - ReferenceError: password is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:68:25)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T14:00:12.811Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:01:42.507Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:01:42.555Z"}
error: 
    status - 500 
    message - ReferenceError: password is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:69:26)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T14:01:45.784Z"}
error: 
    status - 500 
    message - ReferenceError: password is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:69:26)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T14:01:48.118Z"}
error: 
    status - 500 
    message - ReferenceError: password is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:69:26)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T14:01:49.007Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:02:10.936Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:02:10.965Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T14:02:15.065Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:02:48.147Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:02:48.189Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T14:05:59.753Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:09:41.783Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:09:42.085Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:10:15.659Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:10:15.696Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:10:24.040Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:10:24.072Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:10:35.099Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:10:35.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:10:47.545Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:10:47.572Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:11:07.397Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:11:07.422Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:11:20.833Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:11:20.859Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:37:12)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T14:12:17.807Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:37:12)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T14:12:41.556Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:37:12)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T14:13:07.796Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:13:38.071Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:13:38.107Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:37:12)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T14:14:29.646Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:20:18.787Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:20:18.816Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:20:24.902Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:20:24.926Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-03-01T14:20:32.530Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:22:38.731Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:22:38.755Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:25:36.786Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:25:36.816Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:25:43.956Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:25:43.980Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:25:58.417Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:25:58.440Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:26:09.170Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:26:09.195Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:26:30.574Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:26:30.599Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:26:44.150Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:26:44.178Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:29:14.777Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:29:14.805Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 161
    at JSON.parse (<anonymous>)
    at parse (C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note 
    method - POST 
    IP - ::1
   {"timestamp":"2022-03-01T14:30:34.213Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T14:30:58.627Z"}
info: Connected to the database. {"timestamp":"2022-03-01T14:30:58.648Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:32:53.500Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:32:53.530Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:32:58.619Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:32:58.641Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:33:14.424Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:33:14.445Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:33:38.676Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:33:38.704Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:33:55.995Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:33:56.027Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:34:15.825Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:34:15.850Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:34:31.164Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:34:31.188Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:40:31.225Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:40:31.248Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:40:45.030Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:40:45.053Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:40:55.479Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:40:55.509Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:41:02.742Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:41:02.768Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndUpdate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:2694:19)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/note.service.js:57:44)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\src\services\/note.service.js:56:25)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/note.controller.js:99:42)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:41:05.775Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:41:19.788Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:41:19.813Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:43:39.718Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:43:39.744Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:48:58.854Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:48:58.878Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:49:15.990Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:49:16.016Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:49:22.514Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:49:22.541Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76', isArchived: true }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:50:10.859Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:53:42.590Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:53:42.612Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:53:51.496Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:53:54.497Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:53:55.416Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:53:56.257Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:53:56.968Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:53:57.690Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:53:58.361Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:54:00.128Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:54:00.955Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:58:00.750Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:58:00.780Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T15:58:23.587Z"}
info: Connected to the database. {"timestamp":"2022-03-01T15:58:23.617Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/621e3e1c32885022d86450d5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T15:58:35.176Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:21:22.107Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:21:22.133Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:22:16.127Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:22:16.155Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:23:13.208Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:23:13.234Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: 'login', UserID: '621e2b8de19d9834685ebc76' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T16:24:42.508Z"}
error: 
      status - 400
      message - Authorization token is incorrect 
      url - /api/v1/users/reset 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-03-01T16:26:12.351Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":1346,"messageId":"<f7e47072-b518-f708-aa7d-a132529641bf@LAPTOP>","messageSize":549,"messageTime":800,"rejected":[],"response":"250 2.0.0 OK  1646151930 kb6-20020a17090ae7c600b001bee8664d82sm1225258pjb.35 - gsmtp","timestamp":"2022-03-01T16:27:53.644Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:30:31.310Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:33:18.690Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:33:18.714Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:33:42.789Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:33:42.811Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:36:28.962Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:36:28.985Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTUyMDY5fQ.LRBI_ofySWTBjGYZyFeDZXbS1MF7w4RwpF8fInQALNs 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-03-01T16:39:11.235Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTUyMDY5fQ.LRBI_ofySWTBjGYZyFeDZXbS1MF7w4RwpF8fInQALNs 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-03-01T16:39:23.559Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTUyMDY5fQ.LRBI_ofySWTBjGYZyFeDZXbS1MF7w4RwpF8fInQALNs 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-03-01T16:39:24.666Z"}
error: 
    status - 500 
    message - ReferenceError: password is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:71:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTUyMDY5fQ.LRBI_ofySWTBjGYZyFeDZXbS1MF7w4RwpF8fInQALNs 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:39:39.366Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:40:34.677Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:40:34.699Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTUyMDY5fQ.LRBI_ofySWTBjGYZyFeDZXbS1MF7w4RwpF8fInQALNs 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:40:41.558Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:41:08.676Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:41:08.708Z"}
error: 
    status - 500 
    message - ReferenceError: password is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:72:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:76:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTUyMDY5fQ.LRBI_ofySWTBjGYZyFeDZXbS1MF7w4RwpF8fInQALNs 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:41:11.455Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:41:39.116Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:41:39.143Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbElEIjoiYW5hbmR1YmFsZTExQGdtYWlsLmNvbSIsImlkIjoiNjIxMzdhY2Y0YmEwOWQyNjA4NzcxNWNmIiwiaWF0IjoxNjQ2MTUyMDY5fQ.LRBI_ofySWTBjGYZyFeDZXbS1MF7w4RwpF8fInQALNs 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:41:43.714Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:41:55.681Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:41:55.705Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:42:05.275Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:42:05.309Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:42:13.952Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:42:15.779Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:42:16.727Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:44:23.901Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:44:23.927Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:44:31.346Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:44:31.374Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:44:34.193Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:44:50.656Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:44:50.684Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:44:55.507Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:46:08.072Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:46:08.097Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:46:11.497Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:49:18.551Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:49:18.577Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:68:17)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:64:27)
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\controllers\/user.controller.js:77:49)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:49:26.235Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:49:42.359Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:49:42.387Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf', password: 'asdfghjkl' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:49:45.762Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:50:17.243Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:50:17.270Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf', password: 'password' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:50:24.713Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:50:54.364Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:50:54.389Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf', password: 'asdfghjkl' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:51:00.713Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf', password: 'asdfghjkl' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:51:02.909Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:51:47.074Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:51:47.099Z"}
error: 
    status - 500 
    message - Error: Can't use $set
    at ObjectId.SchemaType.castForQuery (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1586:13)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1558:22)
    at cast (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\cast.js:311:39)
    at model.Query.Query.cast (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4937:12)
    at castQuery (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4738:18)
    at model.Query.Query._findAndModify (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:3598:23)
    at model.Query.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:3164:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:279:20
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:103:16)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:508:38
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:51:55.690Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:52:57.371Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:52:57.395Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:53:07.681Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:54:52.383Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:54:52.408Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:55:04.431Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:57:00.494Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:57:00.518Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:57:14.699Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:57:14.725Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:57:18.124Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:57:42.272Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:57:42.301Z"}
error: 
    status - 500 
    message - Error: Can't use $set
    at ObjectId.SchemaType.castForQuery (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1586:13)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1558:22)
    at cast (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\cast.js:311:39)
    at model.Query.Query.cast (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4937:12)
    at castQuery (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4738:18)
    at model.Query.Query._findAndModify (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:3598:23)
    at model.Query.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:3164:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:279:20
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:103:16)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:508:38
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:57:48.719Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:59:08.485Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:59:08.510Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: undefined }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T16:59:13.032Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:59:48.250Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:59:48.276Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T16:59:57.824Z"}
info: Connected to the database. {"timestamp":"2022-03-01T16:59:57.850Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T17:00:05.099Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:04:50.748Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:04:50.774Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ UserID: '62137acf4ba09d26087715cf' }" (type Object) at path "_id" for model "User"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T17:04:55.349Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:05:12.132Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:05:12.158Z"}
error: 
    status - 500 
    message - Error: Can't use $set
    at ObjectId.SchemaType.castForQuery (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1586:13)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1558:22)
    at cast (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\cast.js:311:39)
    at model.Query.Query.cast (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4937:12)
    at castQuery (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4738:18)
    at model.Query.Query._findAndModify (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:3598:23)
    at model.Query.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:3164:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:279:20
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:103:16)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\kareem\index.js:508:38
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T17:05:19.654Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:05:35.023Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:05:35.047Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:05:48.922Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:05:48.970Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:06:31.787Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:06:31.813Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:07:24.035Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:07:24.059Z"}
error: 
    status - 500 
    message - ReferenceError: hashP is not defined
    at _callee5$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:77:24)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/reset 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-03-01T17:07:32.748Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:10:23.145Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:10:23.174Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:10:32.342Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:10:32.373Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:11:03.489Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:11:03.518Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:11:37.056Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:11:37.077Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:12:25.812Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:12:25.842Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:12:46.638Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:12:46.659Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:14:04.728Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:14:04.751Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:14:48.383Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:14:48.405Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:15:29.419Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:15:29.441Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:17:12.476Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:17:12.505Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:17:54.770Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:17:54.791Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:18:07.714Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:18:07.735Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\src\services\/user.service.js:41:9)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-03-01T17:22:53.129Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:26:57.540Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:26:57.562Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:28:48.940Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:28:48.963Z"}
error: 
      status - 400
      message - Authorization token is incorrect 
      url - /api/v1/note/all 
      method - GET 
      IP - ::1
     {"timestamp":"2022-03-01T17:31:17.768Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:33:40.052Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:33:40.077Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:33:51.907Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:33:51.929Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:34:07.593Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:34:07.615Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":1046,"messageId":"<45a7a1b9-2d13-5a96-5709-0826676f68c0@LAPTOP>","messageSize":549,"messageTime":948,"rejected":[],"response":"250 2.0.0 OK  1646156017 n22-20020a056a0007d600b004f11e614565sm17694613pfu.189 - gsmtp","timestamp":"2022-03-01T17:36:01.324Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:37:39.100Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:37:39.122Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-01T17:37:50.620Z"}
info: Connected to the database. {"timestamp":"2022-03-01T17:37:50.641Z"}
info: undefined {"accepted":["anandubale11@gmail.com"],"envelope":{"from":"","to":["anandubale11@gmail.com"]},"envelopeTime":902,"messageId":"<3331623c-d699-4fb4-07a5-7f5109d7c5aa@LAPTOP>","messageSize":549,"messageTime":717,"rejected":[],"response":"250 2.0.0 OK  1646156429 my6-20020a17090b4c8600b001bc2cb011dasm2726352pjb.4 - gsmtp","timestamp":"2022-03-01T17:42:53.222Z"}
