info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T15:01:05.577Z"}
info: Connected to the database. {"timestamp":"2022-02-26T15:01:05.801Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined, UserID: '621a41ee681dae23446ecbfb' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/621a41ee681dae23446ecbfb 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-26T15:11:19.533Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T15:12:57.472Z"}
info: Connected to the database. {"timestamp":"2022-02-26T15:12:57.678Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:128:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-26T15:14:29.595Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T15:19:28.767Z"}
info: Connected to the database. {"timestamp":"2022-02-26T15:19:28.813Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to find() must be an object, got 621a41ee681dae23446ecbfb
    at model.Query.Query.find (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:2098:16)
    at Function.find (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:2157:13)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:59:37)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AllUsers (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:74:18)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:87:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21) 
    url - /api/v1/note/auth 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-26T15:19:39.417Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T15:24:53.491Z"}
info: Connected to the database. {"timestamp":"2022-02-26T15:24:53.533Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T15:26:51.666Z"}
info: Connected to the database. {"timestamp":"2022-02-26T15:26:51.703Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T15:28:37.074Z"}
info: Connected to the database. {"timestamp":"2022-02-26T15:28:37.126Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T15:29:19.976Z"}
info: Connected to the database. {"timestamp":"2022-02-26T15:29:20.016Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T16:39:04.465Z"}
info: Connected to the database. {"timestamp":"2022-02-26T16:39:04.488Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:59:42)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AllUsers (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:75:18)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:87:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/auth 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-26T16:39:14.602Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T16:39:52.722Z"}
info: Connected to the database. {"timestamp":"2022-02-26T16:39:52.745Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined, UserID: '621a41ee681dae23446ecbfb' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/621a4451c3281320c4d88dc6 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-26T16:51:39.651Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T17:03:36.645Z"}
info: Connected to the database. {"timestamp":"2022-02-26T17:03:36.667Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined, UserID: '621a41ee681dae23446ecbfb' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/621a4451c3281320c4d88dc6 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-26T17:03:41.629Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T17:10:03.144Z"}
info: Connected to the database. {"timestamp":"2022-02-26T17:10:03.166Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined, UserID: '621a41ee681dae23446ecbfb' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/621a42ca681dae23446ecbfe 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-26T17:13:00.696Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T17:15:12.131Z"}
info: Connected to the database. {"timestamp":"2022-02-26T17:15:12.198Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-26T17:37:37.297Z"}
info: Connected to the database. {"timestamp":"2022-02-26T17:37:37.320Z"}
