error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-19T03:34:55.318Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/userregister 
      method - GET 
      IP - ::1
     {"timestamp":"2022-02-21T10:43:59.236Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/userregister 
      method - GET 
      IP - ::1
     {"timestamp":"2022-02-21T10:48:10.815Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:39)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T10:53:33.734Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:39)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:38:31.580Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:39)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:39:56.456Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:39)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:39:58.092Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:39)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:39:58.990Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:39)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:39:59.673Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:39)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:40:01.539Z"}
error: 
    status - 500 
    message - ValidationError: "firsName" is required 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:41:28.797Z"}
error: 
    status - 500 
    message - ValidationError: "firsName" is required 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T11:41:29.854Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: password: Cast to string failed for value "Promise { <pending> }" (type Promise) at path "password"
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1349:12)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1058:16)
    at model.Document (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:148:12)
    at model.Model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:106:12)
    at new model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:4911:15)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3157:22
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3193:7
    at Array.forEach (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3192:15
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\index.js:1149:10)
    at Function.create (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3127:23)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:60:37) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T13:28:06.494Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: password: Cast to string failed for value "Promise { <pending> }" (type Promise) at path "password"
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1349:12)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1058:16)
    at model.Document (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:148:12)
    at model.Model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:106:12)
    at new model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:4911:15)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3157:22
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3193:7
    at Array.forEach (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3192:15
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\index.js:1149:10)
    at Function.create (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3127:23)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:60:37) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T13:28:36.937Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: password: Cast to string failed for value "Promise { <pending> }" (type Promise) at path "password"
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1349:12)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1058:16)
    at model.Document (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:148:12)
    at model.Model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:106:12)
    at new model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:4911:15)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3157:22
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3193:7
    at Array.forEach (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3192:15
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\index.js:1149:10)
    at Function.create (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3127:23)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:60:37) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T13:28:37.990Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: password: Cast to string failed for value "Promise { <pending> }" (type Promise) at path "password"
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1349:12)
    at model.$set (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:1058:16)
    at model.Document (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:148:12)
    at model.Model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:106:12)
    at new model (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:4911:15)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3157:22
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3193:7
    at Array.forEach (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3192:15
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\index.js:1149:10)
    at Function.create (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\model.js:3127:23)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:60:37) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T13:28:39.835Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).required(...).unique is not a function
    at newUserValidator (C:\Users\anand\Desktop\fundoo-Notes\build\validators\user.validator.js:16:50)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:174:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-21T16:54:38.051Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/login 
      method - GET 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-02-22T02:43:32.494Z"}
error: 
    status - 500 
    message - ReferenceError: done is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:113:25)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T02:49:43.443Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:31:12.814Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 10 characters long 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:23.141Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:48.887Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:52.108Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:52.981Z"}
error: 
    status - 500 
    message - ReferenceError: hasedPassword is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:102:56)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:33:32.170Z"}
error: uncaughtException: data and hash arguments required
Error: data and hash arguments required
    at Object.compare (C:\Users\anand\Desktop\fundoo-Notes\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\Users\anand\Desktop\fundoo-Notes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\Users\anand\Desktop\fundoo-Notes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:102:48)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Tue Feb 22 2022 10:04:37 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":691102},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\anand\\Desktop\\fundoo-Notes\\build\\index.js"],"cwd":"C:\\Users\\anand\\Desktop\\fundoo-Notes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18366693,"external":24912380,"heapTotal":58310656,"heapUsed":23738072,"rss":68444160},"pid":5444,"uid":null,"version":"v16.13.2"},"stack":"Error: data and hash arguments required\n    at Object.compare (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\bcrypt.js:208:17)\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\promises.js:29:12\n    at new Promise (<anonymous>)\n    at Object.module.exports.promise (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\promises.js:20:12)\n    at Object.compare (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\bcrypt.js:204:25)\n    at _callee3$ (C:\\Users\\anand\\Desktop\\fundoo-Notes\\build\\services\\user.service.js:102:48)\n    at tryCatch (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:63:40)\n    at Generator.invoke [as _invoke] (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:294:22)\n    at Generator.next (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:119:21)\n    at asyncGeneratorStep (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-02-22T04:34:37.399Z","trace":[{"column":17,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\bcrypt.js","function":"Object.compare","line":208,"method":"compare","native":false},{"column":12,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\promises.js","function":null,"line":29,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":12,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\promises.js","function":"Object.module.exports.promise","line":20,"method":"promise","native":false},{"column":25,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\bcrypt\\bcrypt.js","function":"Object.compare","line":204,"method":"compare","native":false},{"column":48,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\build\\services\\user.service.js","function":"_callee3$","line":102,"method":null,"native":false},{"column":40,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js","function":"tryCatch","line":63,"method":null,"native":false},{"column":22,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js","function":"Generator.invoke [as _invoke]","line":294,"method":"invoke [as _invoke]","native":false},{"column":21,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js","function":"Generator.next","line":119,"method":"next","native":false},{"column":24,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:34:37.420Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:47:35.626Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:47:37.102Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:06.132Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:07.496Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:08.121Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:08.534Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:08.874Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:55:25.327Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:55:26.499Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:55:27.294Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:57:20.683Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:58:05.764Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:128:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T06:15:12.973Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:121:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T06:21:04.607Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:121:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T08:31:45.894Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 10 characters long 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T11:37:22.126Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:121:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T11:38:00.762Z"}
error: 
    status - 500 
    message - ValidationError: "emailID" is required 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T03:36:00.904Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: user.users index: emailID_1 dup key: { emailID: "anand@gmail.com" } 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-02-23T03:37:23.028Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\anand\Desktop\fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\error.middleware.js:43:26)
    at Layer.handle_error (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:321:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at Immediate.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:641:15)
    at processImmediate (node:internal/timers:466:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T03:37:23.055Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: user.users index: emailID_1 dup key: { emailID: "anandubale@gmail.com" } 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-02-23T03:37:53.618Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\anand\Desktop\fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\error.middleware.js:43:26)
    at Layer.handle_error (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:321:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at Immediate.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:641:15)
    at processImmediate (node:internal/timers:466:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T03:37:53.621Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: user.users index: emailID_1 dup key: { emailID: "anandubale@gmail.com" } 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-02-23T03:38:44.172Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\anand\Desktop\fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\error.middleware.js:43:26)
    at Layer.handle_error (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:321:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at Immediate.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:641:15)
    at processImmediate (node:internal/timers:466:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T03:38:44.174Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: user.users index: emailID_1 dup key: { emailID: "anandubale@gmail.com" } 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-02-23T03:39:16.787Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\anand\Desktop\fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\error.middleware.js:43:26)
    at Layer.handle_error (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:321:13)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at Immediate.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:641:15)
    at processImmediate (node:internal/timers:466:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T03:39:16.800Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T05:23:43.824Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T05:30:19.952Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T05:33:57.916Z"}
error: 
    status - 500 
    message - ValidationError: "color" is not allowed 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T05:47:14.836Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T05:47:26.787Z"}
error: 
    status - 500 
    message - ValidationError: "color" is not allowed 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T05:49:46.638Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T05:50:21.567Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T06:17:44.045Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T06:17:44.910Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T06:17:45.719Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T06:20:04.241Z"}
error: 
    status - 500 
    message - ValidationError: Note validation failed: Descreption: Path `Descreption` is required., Title: Path `Title` is required.
    at model.Document.invalidate (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T06:20:32.301Z"}
error: 
    status - 500 
    message - TypeError: req.status is not a function
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:167:17)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/6215d3f9fd849145bcb68db3 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T11:40:45.239Z"}
error: 
    status - 500 
    message - TypeError: req.status is not a function
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:167:17)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/6215d3f9fd849145bcb68db3 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T11:44:13.916Z"}
error: 
    status - 500 
    message - TypeError: req.status is not a function
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:167:17)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/6215d3f9fd849145bcb68db3 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T11:44:14.997Z"}
error: 
    status - 500 
    message - TypeError: req.status is not a function
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:167:17)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/6215d3f9fd849145bcb68db3 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T11:44:15.906Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\anand\Desktop\fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:167:56)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/6215d3f9fd849145bcb68db3 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T11:46:16.639Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\anand\Desktop\fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:167:56)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/6215d3f9fd849145bcb68db3 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T11:47:17.937Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "create" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/create 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T11:51:58.266Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:116:20)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateById (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:134:18)
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:164:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/62162b3c8d84732448b08189 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T12:40:55.065Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:116:20)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateById (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:134:18)
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:164:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/62162b3c8d84732448b08189 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T12:41:59.465Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:116:20)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateById (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:134:18)
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:164:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/62162b3c8d84732448b08189 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T12:43:12.475Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:116:20)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateById (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:134:18)
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:164:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/62160a04a3516e3590eda92b 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T12:43:56.965Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:116:20)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateById (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:134:18)
    at _callee4$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:164:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/62162b3c8d84732448b08189 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T12:44:34.475Z"}
error: 
    status - 500 
    message - ValidationError: "UserID" is not allowed 
    url - /api/v1/note/createnote 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-23T12:55:41.531Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "allnotes" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/allnotes 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T04:16:14.415Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "allnotes" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/allnotes 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T05:48:08.196Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected string in JSON at position 93
    at JSON.parse (<anonymous>)
    at parse (C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/ 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T05:52:03.686Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected string in JSON at position 93
    at JSON.parse (<anonymous>)
    at parse (C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/ 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T05:52:11.365Z"}
error: 
    status - 500 
    message - ReferenceError: re is not defined
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:245:44)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:269:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:360:14) 
    url - /api/v1/note/archive/62171d15780805339437cddf 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T05:53:11.237Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:174:20)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:195:18)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:245:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/archive/62171d15780805339437cddf 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T05:59:19.917Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:175:16)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:195:18)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:245:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/archive/62171d15780805339437cddf 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T05:59:54.845Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of undefined (setting 'isArchived')
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:177:43)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/62171d15780805339437cddf 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T06:07:04.324Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of undefined (setting 'isArchived')
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:177:43)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/archive/62171d15780805339437cddf 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T06:07:58.065Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of undefined (setting 'isArchived')
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:175:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:191:18)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:245:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/archive/62171d15780805339437cddf 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T06:14:13.241Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/note/auth/6216fa0dc393083e7ce7d646 
      method - GET 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-02-24T06:54:40.958Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:176:16)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:193:18)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:246:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/archive/6216fa0dc393083e7ce7d646 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T13:51:58.549Z"}
error: 
    status - 500 
    message - ReferenceError: $set is not defined
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:176:16)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:193:18)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:246:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/archive/6216fa0dc393083e7ce7d646 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T13:52:36.530Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'body')
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:176:25)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.MakeArchive (C:\Users\anand\Desktop\fundoo-Notes\build\services\note.service.js:195:18)
    at _callee6$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:246:32)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/note/archive/6216fa0dc393083e7ce7d646 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T13:53:54.703Z"}
error: 
    status - 500 
    message - ReferenceError: re is not defined
    at _callee7$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:284:43)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at DeleteNote (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:308:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:360:14) 
    url - /api/v1/note/delete/62178ee2b60ac7435c602c9f 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T14:02:15.803Z"}
error: 
    status - 500 
    message - ReferenceError: re is not defined
    at _callee7$ (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:284:43)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at DeleteNote (C:\Users\anand\Desktop\fundoo-Notes\build\controllers\note.controller.js:308:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\index.js:360:14) 
    url - /api/v1/note/delete/62178ee2b60ac7435c602c9f 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T14:02:52.744Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '62178ee2b60ac7435c602c9f' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/delete/62178ee2b60ac7435c602c9f 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T14:04:12.866Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "allnotes" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/allnotes 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T14:10:25.798Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 154
    at JSON.parse (<anonymous>)
    at parse (C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/ 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T14:39:46.025Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 154
    at JSON.parse (<anonymous>)
    at parse (C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T14:39:52.090Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 154
    at JSON.parse (<anonymous>)
    at parse (C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\anand\Desktop\fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T14:39:53.527Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:20:40.324Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:119:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:144:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:23:10.033Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:40:56.503Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-24T16:44:39.299Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:56:47.379Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:56:50.513Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:56:51.447Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:56:52.243Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:56:52.961Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:120:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:145:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T16:56:53.973Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:119:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:144:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:03:39.379Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:119:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:144:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:03:40.487Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:06:39.429Z"}
error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at Function.listen (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\anand\Desktop\fundoo-Notes\build\index.js:54:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {"date":"Thu Feb 24 2022 22:38:06 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":909112},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\anand\\Desktop\\fundoo-Notes\\build\\index.js"],"cwd":"C:\\Users\\anand\\Desktop\\fundoo-Notes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19068759,"external":23875794,"heapTotal":59056128,"heapUsed":34026864,"rss":74731520},"pid":17936,"uid":null,"version":"v16.13.2"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1334:16)\n    at listenInCluster (node:net:1382:12)\n    at Server.listen (node:net:1469:7)\n    at Function.listen (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\express\\lib\\application.js:618:24)\n    at Object.<anonymous> (C:\\Users\\anand\\Desktop\\fundoo-Notes\\build\\index.js:54:5)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:17:47","timestamp":"2022-02-24T17:08:06.853Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1334,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1382,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1469,"method":"listen","native":false},{"column":24,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":618,"method":"listen","native":false},{"column":5,"file":"C:\\Users\\anand\\Desktop\\fundoo-Notes\\build\\index.js","function":null,"line":54,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1101,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1153,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":981,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":822,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":17,"method":null,"native":false}]}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:08:54.695Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:09:03.241Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:09:04.776Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:09:05.654Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:09:05.883Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:09:06.071Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "auth" (type string) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\anand\Desktop\fundoo-Notes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:09:06.303Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:119:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:144:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:10:30.450Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee2$ (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:119:45)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at NoteAuth (C:\Users\anand\Desktop\fundoo-Notes\build\middlewares\auth.middleware.js:144:18)
    at Layer.handle [as handle_request] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/note/auth/ 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-24T17:10:33.876Z"}
